# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: OpenTelemetry
description: SPIRE protected OpenTelemetry exporter
version: v0.1.13
slug: otel

host_network: true
full_access: true
docker_api: true
host_dbus: true
privileged:
  - SYS_RAWIO
  - SYS_ADMIN

arch:
  - amd64
  - aarch64

init: false # s6 is init
ports:
  "9100/tcp": 9100

ports_description:
  "9100/tcp": Temp metrics port

image: ghcr.io/alxandr/hass-otel

environment:
  GMAN_HOST: http://supervisor/core/

schema:
  spire:
    address: str
    port: int
    trust_domain: str
    log_level: list(trace|debug|info|warn|error)
    trust_bundle: str
    join_token: password?

options:
  spire:
    address: null
    port: 8081
    trust_domain: null
    log_level: info
    trust_bundle: ""
