# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: G-Man
description: Garage Manager
version: v0.5.2
slug: gman
init: false # Don't use docker's init system, image contains tini
arch:
  - amd64
  - aarch64

homeassistant_api: true

ports:
  "26172/tcp": 26172

ports_description:
  "26172/tcp": The webserver port

image: ghcr.io/alxandr/gman

environment:
  GMAN_HOST: http://supervisor/core/

schema:
  title: str
  script: str
  key: password
  pin: str

options:
  title: Garage Manager
